name       : potrace
version    : 1.14
release    : 1
source     :
    - http://potrace.sourceforge.net/download/1.14/potrace-1.14.tar.gz : db72b65311cfdcb63880b317f610d84485f086e15f88ca2346012d49414cd97e
license    : GPL-2.0
component  : multimedia.graphics
summary    : Potrace is a tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image.
description: |
    Potrace is a tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image.
setup      : |
    %configure --disable-static --with-libpotrace
build      : |
    %make
install    : |
    %make_install
