name       : potrace
version    : 1.15
release    : 3
source     :
    - https://kent.dl.sourceforge.net/project/potrace/1.15/potrace-1.15.tar.gz : a9b33904ace328340c850a01458199e0064e03ccaaa731bc869a842b1b8d529d
license    : GPL-2.0
component  : multimedia.graphics
summary    : Potrace is a tool for tracing a bitmap, which means, transforming a bitmap into a smooth, scalable image
description: |
    Potrace is a tool for tracing a bitmap, which means, transforming a bitmap
    into a smooth, scalable image. A typical use is to create SVG or PDF files
    from scanned data. The resulting image can then be rendered at any
    resolution.
setup      : |
    %configure --disable-static --with-libpotrace
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
